spring:
  application:
    name: helloWorld
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    locale: zh_CN
  datasource:
    name: management
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.19.10:3306/management?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: Ailv123!
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 3
    maxActive: 50
    initialSize: 10
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
#    serialization:
#      write-dates-as-timestamps: true
server:
  port: 8062
  undertow:
    io-threads: 4
    worker-threads: 16
mybatis:
  type-aliases-package: com.zhonghuilv.management.pojo
  #驼峰
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mysql/*.xml